spring:
  application:
    name: device
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:postgresDB}
    hikari:
      username: postgres
      password: ${POSTGRES_PASSWORD:passwd456}
      maximum-pool-size: 10
